### ISSUE TITLE
Update failing tests

### ISSUE THREAD

**Issue by AkshatBajaj** [doubtfire-lms/doubtfire-api#199]
<img width="1097" alt="Screen Shot 2019-10-01 at 8 38 40 am" src="https://user-images.githubusercontent.com/32318980/65921893-eac24080-e426-11e9-8153-bfe1fb4c20b6.png">

**Comment by macite** [comment]
Check that you can generate PDFs on your setup - You should be able to get a task to convert itself to PDF. If there are errors then check the latex error message. This is most likely an issue with your setup, rather than the test itself.
