### ISSUE TITLE
Extension request in the chat

### ISSUE THREAD

**Issue by AkshatBajaj** [doubtfire-lms/doubtfire-api#308]
I am getting a prompt that student has asked for extension for undefined weeks, and when I hit deny it gives already assessed error
<img width="146" alt="Screen Shot 2021-03-16 at 8 07 35 pm" src="https://user-images.githubusercontent.com/32318980/111284367-2b059500-8694-11eb-8866-eae96d47dd2b.png">

**Comment by macite** [comment]
Resolved in latest build
