### ISSUE TITLE
UG-Ontrack Proposal - Integrating Speaker Verification

### ISSUE THREAD

**Issue by kugamigh** [doubtfire-lms/doubtfire-api#314]
We are looking to integrate our Speaker Verification tool within the `doubtfire-api` repository.  In our research, we have found that we will need to make changes to the `discussion_comment_api.rb`, `discussion_comment.rb` and `file_helper.rb` in order to be able to evaluate the audio files with [speaker-verification](https://github.com/OnTrack-UG-Squad/speaker-verification). 

This will only be applied to the replies from students, as verifying the tutor’s discussion prompt is not necessary. The `reply_attachment_path` can be gathered and passed through to our Speaker Verification tool. 

Implementation in `discussion_comment_api.rb` would look similar to this: 

```rb 
# do we need to specify this environment variable somewhere? 
# or is there a os.environ(“SPEAKER_VERIF_PATH”) func we could use? 

if SPEAKER_VERIF_PATH	!= ”” # make sure it is unset... else 
   result  =  discussion_comment.add_reply(attached_file) 
else  
    result, audio_path = discussion_comment.add_speaker_verif_reply(attached_file) 
    # bespoke method to be added to discussion_comment.py utilizing optionParser, 
    # to send python command to command line. 

    result = discussion_comment.process_speaker_verification(current_user.id, audio_path) 

```

**Comment by aidanjgriffiths** [comment]
After thinking about it a bit more, I think we can get the `audio_file_path` through the `discussion_comment` instance like:
```rb
result  =  discussion_comment.add_reply(attached_file) 
if ENV["SPEAKER_VERIF_PATH"].is_set?
    # bespoke method to be added to discussion_comment.py utilizing optionParser, 
    # to send python command to command line. 
    result = discussion_comment.process_speaker_verification(current_user.id, discussion_comment.reply_attachment_path) 
```

**Comment by aidanjgriffiths** [comment]
@kugamigh Could you please Add us, @macite, and @jakerenzella as assignees? 
Worth noting that this work will be completed on the [UG ontrack fork](https://github.com/OnTrack-UG-Squad/doubtfire-api).

**Comment by kugamigh** [comment]
Unfortunately I don't have permissions to assign the issue.  I will need one of the others to help with that part.
