### ISSUE TITLE
Calendar feed returns blank data 

### ISSUE THREAD

**Issue by ublefo** [doubtfire-lms/doubtfire-api#361]
Hi, I've noticed that the calendar feed has always been returning blank data for me containing no events whatsoever. Refreshing, re-selecting, messing with the other options have absolutely no effect. This is all I get from the API:
```
"BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:OnTrack\r\nCALSCALE:GREGORIAN\r\nMETHOD:PUBLISH\r\nX-PUBLISHED-TTL;VALUE=DURATION:P1D\r\nREFRESH-INTERVAL;VALUE=DURATION:P1D\r\nEND:VCALENDAR\r\n"
```

I have tried emailing the support email within the university back in 2021 but the communication has stopped altogether shortly after and I did not hear back from them ever since. Adding the due dates in a calendar manually is extremely cumbersome, please fix this asap so I can manage my workload properly.

**Comment by ublefo** [comment]
So I did some digging and isolated a few bugs. I might close this issue and create new issues as there are several different underlying problems causing this. Will investigate deeper later this week if time permits.

1. The returned data is not a valid iCalendar file, it's raw JSON, which is not accepted by any calendar applications. This is a new issue after the backend update as doubtfire-api did return valid iCalendar files in 2021.
2. The API somehow will _only_ return non-empty iCalendar files during week 1 (after Tuesday or so), even though units are already accessible by students during the week before. In no way is this communicated anywhere in the UI. This either needs to be clearly communicated to the users in doubtfire-web, or this limitation needs to be removed and make availability synchronized with the unit availability through doubtfire-web. In other words, as soon as the unit is marked as "active", the due dates should be made available in the iCalendar feed.
3. There seems to be a superficial limit on the amount of tasks that is included in the iCalendar feed. I need to do some scripting to test my theory but basically doubtfire-api is unable to cope with tasks from more than one unit. I would get most of the tasks from one unit, one or two from the other one, and none from everything else. The only way to mitigate this so far is to manually change the exclusion rules and exclude all but one unit, query the API to get the calendar feed, and then swap in another unit, rinse and repeat.

**Comment by macite** [comment]
Sounds like playing around with the webcal task definitions query would be a good place to start. If you setup some unit tests that mimic the issue then you can make sure the fix will address the issue.

**Comment by ublefo** [comment]
Looks like this has been fixed, I tested it again and there are no malformed iCalendar data nor missing tasks anymore, thank you.
