### ISSUE TITLE
Incorrect rendering of blank user nicknames in group listing

### ISSUE THREAD

**Issue by lindenhutchinson** [doubtfire-lms/doubtfire-api#363]
If a user has set their nickname and then removed it, () will be rendered next to their name in the group list page.

**Comment by jakerenzella** [comment]
Closed and referenced in a new issue in doubtfire-web.

**Comment by lindenhutchinson** [comment]
This issue is caused by how student_name is set in doubtfire-api/app/api/entities/project_entity.rb @jakerenzella
