### ISSUE TITLE
CORS Issues

### ISSUE THREAD

**Issue by QuantumImmortality** [doubtfire-lms/doubtfire-api#72]
Hi, strictly this isn't an issue but I'm having so much trouble trying to get this to work and thought this was the best place to post.

I have the doubtfire-api up and running on a cloud hosted server. I can curl the ../api/docs and get a 200 response from the external computer. However, my issue is with CORS I believe and trying to connect to the website from a computer external to the server. I've tried with Chrome, Mozilla, and Edge browsers.

I added this to the `/doubtfire-api/config/application.rb` as an alternative to what was already there:
 `config.middleware.insert_before 0, "Rack::Cors" do
      allow do
        origins '*'
        resource '*', :headers => :any, :methods => [:get, :post, :options]
      end
    end`

Neither what was there or what I changed it to above worked.

So when I try to connect to the /api/docs externally, swagger pops up and gives me this output only:

> Can't read from server. It may not have the appropriate access-control-origin settings.

Any idea what I'm missing or suggestions?

**Comment by macite** [comment]
The Swagger API doesn't automatically locate the APP when deployed. Enter the URL of the api directory then click the Explore button. It should then work.

I also suggest deploying the Development branch, we need to replace Master but haven't.

**Comment by macite** [comment]
You should be able to access the swagger file yourself to check the URL...

**Comment by QuantumImmortality** [comment]
Alright, thanks, I'll deploy the Dev branch :)
