### ISSUE TITLE
BUG: User email regex accepting invalid emails

### ISSUE THREAD

**Issue by akashagarwal7** [doubtfire-lms/doubtfire-api#92]
The email address regex for users API doesn’t seem to be working properly. I’m able to create accounts with these emails: `qwertyuiop@qwe qwertyuiop@.com qwertyuiop@blah..com`. I haven't tried more combinations at the moment.
The bug can be reproduced using Swagger or the follow minitest:
```
  def test_post_create_user_invalid_email
    pre_count = User.all.length
    user = {
        first_name: 'Akash',
        last_name: 'Agarwal',
        email: 'blah@blah.com',
        username: 'akash',
        nickname: 'akash',
        system_role: 'Admin'
    }

    invalid_emails = %w(qwertyuiop qwertyuiop@qwe qwertyuiop@.com qwertyuiop@blah..com)

    invalid_emails.each do |email|
      # Assign invalid email
      user[:email] = email

      data_to_post = {
          user: user,
          auth_token: auth_token
      }

      post_json '/api/users', data_to_post
      # Successful assertion of same length again means no record was created
      assert_equal pre_count, User.all.length
      assert_equal 500, last_response.status
    end
  end
```

**Comment by akashagarwal7** [comment]
The `user.rb` file was last edited in 2012. This is the [commit](https://github.com/doubtfire-lms/doubtfire-api/commit/6bbcedcdda2888aac5be021efb2b29c033c13bfb).
The regex used in `user.rb` seems to be taken from [here](https://apidock.com/rails/ActiveModel/Validations/HelperMethods/validates_format_of)

**Comment by akashagarwal7** [comment]
The regex used in `user.rb` at [line 445](https://github.com/doubtfire-lms/doubtfire-api/blob/0f1a34dec520fdb2b30693e3ec1181460c35c111/app/models/user.rb#L445) seems to be taken from [here](https://apidock.com/rails/ActiveModel/Validations/HelperMethods/validates_format_of)

**Comment by macite** [comment]
This would be a good PR

**Comment by akashagarwal7** [comment]
@macite Why do we have escaped characters 'A' and 'z' in the regex `\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z`? Also, are we considering gmail like email addresses (for example asd.asd@gmail.com) valid?

**Comment by macite** [comment]
Would have to look... guessing it should be matching start and end of string

**Comment by akashagarwal7** [comment]
I see, thanks for clearing that out. This seems to be ruby specific.

**Comment by akashagarwal7** [comment]
#93 fixes this.
